### ISSUE TITLE
Parse PCHSTRAP entries

### ISSUE THREAD

**Issue by Mimoja** [Mimoja/ifdutil#9]
Is this universal threw all  the PCH versions?

**Comment by heijligen** [comment]
no, as you can see at the length of this entry each 'version' has his own pchstrap area.
FLMAP1 31:24

**Comment by Mimoja** [comment]
The different fields of the PCHSTRAP area seem to be universal, while the number of PCHSTRAP "CONTAINERS" differs

**Comment by heijligen** [comment]
no, there haven't the same content. for example 6 Series Chipset has the BIOS boot block size at PCHSTRAP0 and Skylake lp hast multible other settings there like DCI/JTAGoverUSB enable etc

**Comment by Mimoja** [comment]
Wontfix!
